apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: ninjaops/frontend:16
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30004
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: front