apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ninjaops/frontend:15
        ports:
          - containerPort: 80
        env:
        - name: REACT_APP_SERVER_BASE_URL
          value: "http://localhost:8091"
        - name: REACT_APP_WS_BASE_URL
          value: "ws://localhost:8888"
        - name: NODE_ENV
          value: "production"
        - name: PUBLIC_URL
          value: "http://localhost:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend