apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: ninjaops/frontend:15
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_SERVER_BASE_URL
              value: "http://192.168.199.134:8091"
            - name: REACT_APP_WS_BASE_URL
              value: "ws://192.168.199.134:80"
            - name: NODE_ENV
              value: "production"
            - name: PUBLIC_URL
              value: "http://192.168.199.134:80"

---

apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
  selector:
    app: front