apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-user-deployment
  labels:
    app: microservice-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-user
  template:
    metadata:
      labels:
        app: microservice-user
    spec:
      containers:
      - name: microservice-user
        image: ninjaops/microservice-user
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-user-service
spec:
  type: ClusterIP
  selector:
    app: microservice-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080