apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-product-deployment
  labels:
    app: microservice-product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-product
  template:
    metadata:
      labels:
        app: microservice-product
    spec:
      containers:
      - name: microservice-product
        image: ninjaops/microservice-product:1
        ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-product-service
spec:
  type: ClusterIP
  selector:
    app: microservice-product
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081