apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-cart-deployment
  labels:
    app: microservice-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-cart
  template:
    metadata:
      labels:
        app: microservice-cart
    spec:
      containers:
      - name: microservice-cart
        image: ninjaops/microservice-cart:3
        ports:
          - containerPort: 8082
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URL
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_USER
          - name: USER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: USER_SERVICE_URL
          - name: USER_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: USER_SERVICE_PORT
          - name: PRODUCT_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PRODUCT_SERVICE_URL
          - name: PRODUCT_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PRODUCT_SERVICE_PORT
          - name: HOST_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: HOST_URL
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-cart-service
spec:
  type: ClusterIP
  selector:
    app: microservice-cart
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082