apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-gateway-deployment
  labels:
    app: microservice-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-gateway
  template:
    metadata:
      labels:
        app: microservice-gateway
    spec:
      containers:
      - name: microservice-gateway
        image: ninjaops/microservice-gateway:1
        ports:
          - containerPort: 8091
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URL
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_USER
          - name: AUTH0_ISSUER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: AUTH0_ISSUER
          - name: HOST_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: HOST_URL

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-gateway-service
spec:
  type: ClusterIP
  selector:
    app: microservice-gateway
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091