apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-gateway-deployment
  labels:
    app: microservice-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-gateway
  template:
    metadata:
      labels:
        app: microservice-gateway
    spec:
      containers:
      - name: microservice-gateway
        image: ninjaops/microservice-gateway:1
        ports:
          - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-gateway-service
spec:
  type: ClusterIP
  selector:
    app: microservice-gateway
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091