apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-cart-deployment
  labels:
    app: microservice-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-cart
  template:
    metadata:
      labels:
        app: microservice-cart
    spec:
      containers:
      - name: microservice-cart
        image: ninjaops/microservice-cart
        ports:
          - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-cart-service
spec:
  type: ClusterIP
  selector:
    app: microservice-cart
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082