apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-product-deployment
  labels:
    app: microservice-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-product
  template:
    metadata:
      labels:
        app: microservice-product
    spec:
      containers:
      - name: microservice-product
        image: ninjaops/microservice-product:3
        ports:
          - containerPort: 8081
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URL
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_USER
          - name: HOST_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: HOST_URL
          - name: ELASTICSEARCH_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ELASTICSEARCH_URL
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ELASTICSEARCH_PASSWORD
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: REDIS_URL
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: REDIS_PORT
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-product-service
spec:
  type: ClusterIP
  selector:
    app: microservice-product
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081