apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-gateway-deployment
  labels:
    app: microservice-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-gateway
  template:
    metadata:
      labels:
        app: microservice-gateway
    spec:
      containers:
      - name: microservice-gateway
        image: ninjaops/microservice-gateway:5
        ports:
          - containerPort: 8091
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URL
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_USER
          - name: AUTH0_ISSUER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: AUTH0_ISSUER
          - name: AUTH0_USERINFO_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: AUTH0_USERINFO_URL
          - name: USER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: USER_SERVICE_URL
          - name: USER_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: USER_SERVICE_PORT
          - name: CART_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: CART_SERVICE_URL
          - name: CART_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: CART_SERVICE_PORT
          - name: PRODUCT_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PRODUCT_SERVICE_URL
          - name: PRODUCT_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PRODUCT_SERVICE_PORT
          - name: ORDER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ORDER_SERVICE_URL
          - name: ORDER_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ORDER_SERVICE_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-gateway-service
spec:
  type: NodePort
  selector:
    app: microservice-gateway
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091