# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-script
          image: postgres:14.7
          command: ['sh', '-c', 'cp /host-scripts/install-pgcrypto.sh /docker-entrypoint-initdb.d/install-pgcrypto.sh && chmod +x /docker-entrypoint-initdb.d/install-pgcrypto.sh']
          volumeMounts:
            - name: host-scripts
              mountPath: /host-scripts
            - name: postgredb
              mountPath: /var/lib/postgresql/data
        - name: init-database
          image: postgres:14.7
          command: ['sh', '-c', 'psql -U postgres -f /host-scripts/init-database.sql']
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: host-scripts
              mountPath: /host-scripts
            - name: postgredb
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:14.7
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: host-scripts
          hostPath:
            path: /home/kubeuser

---
# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432