apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ecomm-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postegresql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ecomm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
